### ISSUE TITLE
When will the release for ver 2.0 be carried out?

### ISSUE THREAD

**Issue by plainsquirrel** [FabianLars/tauri-plugin-oauth#26]
Hi, I'm preparing to start a project with tauri 2.0 and sveltekit. I'm trying to configure a login using Oauth, and that plug-in seems to be the most appropriate. According to the most recent commit, I have 2.0, and I wonder when the version-up plan will be. (I want to contribute, but I haven't really figured out the tauri ecosystem yet.)

**Comment by FabianLars** [comment]
You can use the [v2 branch](https://github.com/FabianLars/tauri-plugin-oauth/tree/v2) for now:
```toml
[dependencies]
tauri-plugin-oauth = { git = "https://github.com/FabianLars/tauri-plugin-oauth", branch = "v2" }
```

I am currently out of office due to sickness but once i have access to my computer i'll release new versions.
